### ISSUE TITLE
block.digTime does not correctly handle Conduit Power status effect

### ISSUE THREAD

**Issue by Archengius** [PrismarineJS/prismarine-block#35]
When Conduit was introduced, new status effect appeared related to it.
According to MC code, it works exactly like Haste and game pretty much uses effect with higher amplifier
currently, conduit power will not be accounted for break speed buff

**Comment by u9g** [comment]
digTime is based on this calculation: https://minecraft.fandom.com/wiki/Breaking

**Comment by Archengius** [comment]
yeah, and according to the decompiled code of 1.17, this calculation is obsolete

**Comment by rom1504** [comment]
is that fixed in your latest pr @Archengius ?

**Comment by Archengius** [comment]
Yeah, it is
